users:
  - user:
      #username 学号或者工号
      username: 18305199
      #password 密码
      password: '******'
      #address 地址
      address: 中国四川省广元清华大学
      #email 接受通知消息的邮箱
      email: i@163.com
      #school 学校全称
      school: 四川信息职业技术学院
      #photo 查寝图片
      photo: '1.jpg'
# 多用户配置
  - user:
      #username 学号或者工号
      username: 18305232
      #password 密码
      password: '******'
      #address 地址
      address: 中国四川省广元清华大学
      #email 接受通知消息的邮箱
      email: i@163.com
      #school 学校全称
      school: 四川信息职业技术学院
      #photo 查寝图片
      photo: '2.jpg'
# 今日校园表单相关配置
cpdaily:
  # 表单组默认选项配置
  defaults:
    # 表单默认选项配置，按顺序
    - default:
        # 表单项类型，对应今日校园接口返回的fieldType字段，2代表单选，1代表文本
        type: 2
        #表单项标题
        title: 当前体温
        # 表单项默认值
        value: <37.3℃
    - default:
        type: 1
        title: 实测体温（℃）
        value: 36.5
    - default:
        type: 2
        title: 当前身体状况
        value: 正常
    - default:
        type: 2
        title: 学生公寓
        value: 雪峰校区4#公寓
    - default:
        type: 1
        title: 寝室号
        value: 4129
